# Generated by Django 4.2.4 on 2023-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('isComplete', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'isComplete'], name='todo_app_to_item_82d5dc_idx')],
            },
        ),
    ]
